# Site
name: "애플 CHKCHK(첵첵)"
title: "애플 판매 가격 동향"
description: "애플 아이폰 자급제, 아이패드, 애플워치, 갤럭시S23 자급제, 갤럭시탭 S8 "
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: 'http://www.chkchk.co.kr'
baseurl: ''
google_analytics: 'G-FRLYY7SFLH'
disqus: 'iphone-chkchk-co-kr'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  IPHONE:
    name: IPHONE
    display_name: 아이폰
    avatar: 'assets/images/avatar_iphone.png'
    description: "아이폰을 쓰는 이유 1.디자인 · 2.성능 · 3.가격 방어, 중고 가격 · 4.애플의 사후지원, 소프트웨어 업데이트 · 5.애플 생태계의 연동성"
  APPLEWATCH:
    name: APPLEWATCH
    display_name: 애플워치
    avatar: 'assets/images/avatar_applewatch.png'
    description: " 애플 워치는 높은 완성도의 디자인을 갖추고 있습니다. 또한 스마트워치의 경우 같은 제조회사에서 만든 스마트폰만 연동되기 때문에 사용하는 스마트폰에 따라 결정하시면 되겠습니다."
  IPAD:
    name: IPAD
    display_name: 아이패드
    avatar: 'assets/images/avatar_ipad.png'
    description: "스피커가 4개나 탑재되어 있어서 영상 시청을 하거나 음악 감상 시 사운드가 훌륭하다. ✔️ 라미네이팅 기능으로 인해 메모나 그림 등 필기감이 많이 우수하다. ✔️ 주사율을 120Hz까지 지원하기 때문에 화면 움직임이 매우 부드럽다."
  COSTCO:
    name: COSTCO
    display_name: 코스트코
    avatar: 'assets/images/costco/costco_avatar.jfif'
    description: "코스트코 애플 아이폰/아이패드 제품이 오프라인 최저가인 사실 아셨나요? 세일에 코스트코 적립 5%까지 더하면 쿠팡가격보다 쌀때도 있습니다."
  GALAXY:
    name: GALAXY
    display_name: 갤럭시
    avatar: 'assets/images/galaxy/galaxy.png'
    description: "삼성 갤럭시"    

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# disabled
adsense: "enabled"
adsense-data-ad-client: "ca-pub-9700808607953087"
adsense-data-ad-slot: "6129709832"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

#include: 
#  \- .nojekyll
  
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
